apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-1
  name: mysql-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql-1
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: lana
        - name: MYSQL_DATABASE
          value: task-manager
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
