apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-service
  name: task-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - image: lanaradmilovic/taskservice:0.0.2.RELEASE
          imagePullPolicy: IfNotPresent
          name: taskservice
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-1:3306/task-manager
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: lana
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: task-service
  name: task-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  ports:
    - nodePort: 30536
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: task-service
  sessionAffinity: None
  type: LoadBalancer
