---
- name: Deploy Docker Container
  hosts: all
  become: true
  vars:
    docker_image: "lanaradmilovic/taskservice:{{ docker_image }}"
    container_name: "task-service-container"

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: latest
        state: present

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
